/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type DeleteApplicationsApplicationIdFilesFileBody = {
  /** Путь к файлу, который необходимо удалить. */
  filePath?: string;
};
