/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import type { FileSystemItemType } from './fileSystemItemType';

export interface FileSystemItem {
  name?: string;
  type?: FileSystemItemType;
  path?: string;
  children?: FileSystemItem[];
}
