/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type FileSystemItemType = typeof FileSystemItemType[keyof typeof FileSystemItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileSystemItemType = {
  file: 'file',
  directory: 'directory',
} as const;
