/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import type { IMongoModelApplication } from './iMongoModelApplication';

export type GetApplications200 = {
  applications?: IMongoModelApplication[];
};
