/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplicationsApplicationIdMessages200ItemPromtsItem } from './getApplicationsApplicationIdMessages200ItemPromtsItem';

export type GetApplicationsApplicationIdMessages200Item = {
  /** Идентификатор сообщения. */
  id?: string;
  /** Содержимое сообщения. */
  content?: string;
  /** Роль отправителя (user или assistant). */
  role?: string;
  /** Статус сообщения. */
  status?: string;
  /** Список промтов, связанных с сообщением. */
  promts?: GetApplicationsApplicationIdMessages200ItemPromtsItem[];
};
