/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type GetApplicationsApplicationIdMessages200Item = {
  /** Содержимое сообщения или промта. */
  content?: string;
  /** Роль отправителя (user или assistant). */
  role?: string;
  /** Статус сообщения или промта. */
  status?: string;
};
