/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EaseAppz API
 * API documentation for EaseAppz
 * OpenAPI spec version: 1.0.0
 */

export type GetApiApplicationzsApplicationzIdMessages200Item = {
  _id?: string;
  content?: string;
  applicationz?: string;
  role?: string;
  chatgptId?: string;
  chatgptThreadId?: string;
  createdAt?: string;
  updatedAt?: string;
};
