/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import type { GetConfig200TemplatesItem } from './getConfig200TemplatesItem';
import type { GetConfig200ServicesItem } from './getConfig200ServicesItem';

export type GetConfig200 = {
  templates?: GetConfig200TemplatesItem[];
  services?: GetConfig200ServicesItem[];
};
