/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import type { GetConfig200TemplatesItem } from './getConfig200TemplatesItem';

export type GetConfig200 = {
  /** Список шаблонов приложения. */
  templates?: GetConfig200TemplatesItem[];
  /** Список ключей (идентификаторов) моделей AI. */
  modelsAi?: string[];
};
