/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type GetUser200 = {
  /** Идентификатор пользователя */
  _id?: string;
  /** Email пользователя */
  email?: string;
  /** Имя пользователя */
  name?: string;
  /** Код пользователя */
  code?: string;
};
