/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль отправителя сообщения
 */
export type IMongoModelMessageRole = typeof IMongoModelMessageRole[keyof typeof IMongoModelMessageRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IMongoModelMessageRole = {
  user: 'user',
  assistant: 'assistant',
} as const;
