/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export interface IMongoModelLog {
  /** Идентификатор лога. */
  _id?: string;
  /** Идентификатор приложения, к которому привязан лог. */
  application?: string;
  /** Сообщение лога. */
  content?: string;
  type?: string;
  status?: string;
  /** Дата и время создания лога. */
  createdAt?: string;
}
