/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type PostPromtsAnalyze200 = {
  /** Имя, назначенное на основе анализа */
  name?: string;
  /** Описание, сформированное на основе сообщения */
  description?: string;
  /** Выбранный шаблон */
  template?: string;
  /** Выбранный сервис */
  service?: string;
};
