/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EaseAppz API
 * API documentation for EaseAppz
 * OpenAPI spec version: 1.0.0
 */

export type PostApiApplicationzs201 = {
  _id?: string;
  template?: string;
  pending?: boolean;
  pendingPercent?: number;
  createdAt?: string;
  updatedAt?: string;
};
