/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type PostApplicationsBody = {
  /** Название приложения. */
  name?: string;
  /** Описание приложения. */
  description?: string;
  /** Шаблон приложения. */
  template?: string;
  /** Модель искусственного интеллекта. */
  modelAi?: string;
};
