/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type PostUser201 = {
  /** Статус ошибки */
  error?: boolean;
  /** Сообщение о статусе */
  message?: string;
};
