/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EaseAppz API
 * API documentation for EaseAppz
 * OpenAPI spec version: 1.0.0
 */

export type PostApiApplicationzsApplicationzIdMessagesBody = {
  content?: string;
};
