/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type PutApplicationsApplicationIdFilesFileBody = {
  /** Путь к файлу, который необходимо обновить. */
  filePath?: string;
  /** Новое содержимое файла. */
  content?: string;
};
