/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApplications200,
  GetApplications401,
  GetApplications500,
  IMongoModelApplication,
  PostApplications400,
  PostApplications500,
  PostApplicationsBody
} from './types'
import getApplicationsMutator from '../axios';
import type { ErrorType as GetApplicationsErrorType } from '../axios';
import postApplicationsMutator from '../axios';
import type { ErrorType as PostApplicationsErrorType } from '../axios';




/**
 * Возвращает список всех приложений, принадлежащих аутентифицированному пользователю (req.user).
 * @summary Получение списка приложений для пользователя
 */
export const getApplications = (
    
 signal?: AbortSignal
) => {
      
      
      return getApplicationsMutator<GetApplications200>(
      {url: `/applications`, method: 'GET', signal
    },
      );
    }
  

export const getGetApplicationsQueryKey = () => {
    return [`/applications`] as const;
    }

    
export const getGetApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplications>>> = ({ signal }) => getApplications(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApplications>>>
export type GetApplicationsQueryError = GetApplicationsErrorType<GetApplications401 | GetApplications500>


export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Получение списка приложений для пользователя
 */

export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApplicationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Создает новое приложение с указанными параметрами.
 * @summary Создание нового приложения
 */
export const postApplications = (
    postApplicationsBody: PostApplicationsBody,
 signal?: AbortSignal
) => {
      
      
      return postApplicationsMutator<IMongoModelApplication>(
      {url: `/applications`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApplicationsBody, signal
    },
      );
    }
  


export const getPostApplicationsMutationOptions = <TError = PostApplicationsErrorType<PostApplications400 | PostApplications500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext> => {
    
const mutationKey = ['postApplications'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApplications>>, {data: PostApplicationsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApplications(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApplicationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApplications>>>
    export type PostApplicationsMutationBody = PostApplicationsBody
    export type PostApplicationsMutationError = PostApplicationsErrorType<PostApplications400 | PostApplications500>

    /**
 * @summary Создание нового приложения
 */
export const usePostApplications = <TError = PostApplicationsErrorType<PostApplications400 | PostApplications500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApplications>>,
        TError,
        {data: PostApplicationsBody},
        TContext
      > => {

      const mutationOptions = getPostApplicationsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    