/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  PostApplicationsApplicationIdMessagesMessageIdRetry200,
  PostApplicationsApplicationIdMessagesMessageIdRetry404,
  PostApplicationsApplicationIdMessagesMessageIdRetry500
} from './types'
import postApplicationsApplicationIdMessagesMessageIdRetryMutator from '../axios';
import type { ErrorType as PostApplicationsApplicationIdMessagesMessageIdRetryErrorType } from '../axios';




/**
 * Находит сообщение по идентификатору, проверяет существование связанного приложения, обновляет все промты  с статусом "error" на "created" для этого сообщения и отправляет его в очередь для срочной обработки.

 * @summary Повторная обработка промтов сообщения
 */
export const postApplicationsApplicationIdMessagesMessageIdRetry = (
    applicationId: string,
    messageId: string,
 signal?: AbortSignal
) => {
      
      
      return postApplicationsApplicationIdMessagesMessageIdRetryMutator<PostApplicationsApplicationIdMessagesMessageIdRetry200>(
      {url: `/applications/${applicationId}/messages/${messageId}/retry`, method: 'POST', signal
    },
      );
    }
  


export const getPostApplicationsApplicationIdMessagesMessageIdRetryMutationOptions = <TError = PostApplicationsApplicationIdMessagesMessageIdRetryErrorType<PostApplicationsApplicationIdMessagesMessageIdRetry404 | PostApplicationsApplicationIdMessagesMessageIdRetry500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>, TError,{applicationId: string;messageId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>, TError,{applicationId: string;messageId: string}, TContext> => {
    
const mutationKey = ['postApplicationsApplicationIdMessagesMessageIdRetry'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>, {applicationId: string;messageId: string}> = (props) => {
          const {applicationId,messageId} = props ?? {};

          return  postApplicationsApplicationIdMessagesMessageIdRetry(applicationId,messageId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApplicationsApplicationIdMessagesMessageIdRetryMutationResult = NonNullable<Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>>
    
    export type PostApplicationsApplicationIdMessagesMessageIdRetryMutationError = PostApplicationsApplicationIdMessagesMessageIdRetryErrorType<PostApplicationsApplicationIdMessagesMessageIdRetry404 | PostApplicationsApplicationIdMessagesMessageIdRetry500>

    /**
 * @summary Повторная обработка промтов сообщения
 */
export const usePostApplicationsApplicationIdMessagesMessageIdRetry = <TError = PostApplicationsApplicationIdMessagesMessageIdRetryErrorType<PostApplicationsApplicationIdMessagesMessageIdRetry404 | PostApplicationsApplicationIdMessagesMessageIdRetry500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>, TError,{applicationId: string;messageId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApplicationsApplicationIdMessagesMessageIdRetry>>,
        TError,
        {applicationId: string;messageId: string},
        TContext
      > => {

      const mutationOptions = getPostApplicationsApplicationIdMessagesMessageIdRetryMutationOptions(options);

      return useMutation(mutationOptions);
    }
    