/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApplicationsIdLogs200,
  GetApplicationsIdLogs400,
  GetApplicationsIdLogs500
} from './types'
import getApplicationsIdLogsMutator from '../axios';
import type { ErrorType as GetApplicationsIdLogsErrorType } from '../axios';




/**
 * Возвращает список логов для указанного приложения.
 * @summary Получить логи приложения
 */
export const getApplicationsIdLogs = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return getApplicationsIdLogsMutator<GetApplicationsIdLogs200>(
      {url: `/applications/${id}/logs`, method: 'GET', signal
    },
      );
    }
  

export const getGetApplicationsIdLogsQueryKey = (id: string,) => {
    return [`/applications/${id}/logs`] as const;
    }

    
export const getGetApplicationsIdLogsQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationsIdLogsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationsIdLogs>>> = ({ signal }) => getApplicationsIdLogs(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApplicationsIdLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationsIdLogs>>>
export type GetApplicationsIdLogsQueryError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>


export function useGetApplicationsIdLogs<TData = Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationsIdLogs>>,
          TError,
          Awaited<ReturnType<typeof getApplicationsIdLogs>>
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationsIdLogs<TData = Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationsIdLogs>>,
          TError,
          Awaited<ReturnType<typeof getApplicationsIdLogs>>
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationsIdLogs<TData = Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Получить логи приложения
 */

export function useGetApplicationsIdLogs<TData = Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError = GetApplicationsIdLogsErrorType<GetApplicationsIdLogs400 | GetApplicationsIdLogs500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationsIdLogs>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApplicationsIdLogsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



